<a href="https://colab.research.google.com/github/consor92/Probabilidad_aplicada/blob/Clase_Init_R/Taller_de_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Taller de R

1) Cargar el dataset iris (ya viene incluido en R)
data(iris)

In [1]:
datos <-iris

2) Dimensiones del data frame:
dim(iris)      

3) Nombres de las columnas:
colnames(iris)

4) Visualización de extremos (para ver las primeras y últimas filas)
* head(iris)     (Primeras 6 filas)
* tail(iris)     (Últimas 6 filas)

5) Estructura interna (tipos de datos)
str(iris)      # num, num, num, num, Factor

6) Resumen estadístico completo
summary(iris)

In [12]:
print('--- Dimensiones del DataFrame ---')
dim(datos)

print('\n--- Nombres de las Columnas ---')
colnames(datos)

print('\n--- Primeras 6 Filas (head) ---')
head(datos)

print('\n--- Últimas 6 Filas (tail) ---')
tail(datos)

print('\n--- Estructura Interna (str) ---')
str(datos)

print('\n--- Resumen Estadístico (summary) ---')
summary(datos)

[1] "--- Dimensiones del DataFrame ---"

[1] 150   5

[1] "\n--- Nombres de las Columnas ---"

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

[1] "\n--- Primeras 6 Filas (head) ---"

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

[1] "\n--- Últimas 6 Filas (tail) ---"

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

[1] "\n--- Estructura Interna (str) ---"
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
[1] "\n--- Resumen Estadístico (summary) ---"

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300
 Median :5.800   Median :3.000   Median :4.350   Median :1.300
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500
       Species
 setosa    :50
 versicolor:50
 virginica :50

7) Calcular la media y el desvío de cada variable:

* Media de cada variable numérica
mean(iris$nombrevaribale)


* Desvío estándar muestral
sd(iris$nombrevariable)

In [31]:
print('--- Sepal.Length ---')
cat(sprintf("Media de Sepal.Length: %.2f\n", mean(datos$Sepal.Length)))
cat(sprintf("Desvío estándar de Sepal.Length: %.2f\n", sd(datos$Sepal.Length)))

[1] "--- Sepal.Length ---"
Media de Sepal.Length: 5.84
Desvío estándar de Sepal.Length: 0.83

In [25]:
print('--- Sepal.Width ---')
cat(sprintf("Media de Sepal.Width: %.2f\n", mean(datos$Sepal.Width)))
cat(sprintf("Desvío estándar de Sepal.Width: %.2f\n", sd(datos$Sepal.Width)))

[1] "--- Sepal.Width ---"
Media de Sepal.Width: 3.06
Desvío estándar de Sepal.Width: 0.44

In [23]:
print('--- Petal.Length ---')
cat(sprintf("Media de Petal.Length: %.2f\n", mean(datos$Petal.Length)))
cat(sprintf("Desvío estándar de Petal.Length: %.2f\n", sd(datos$Petal.Length)))

[1] "--- Petal.Length ---"
Media de Petal.Length: 3.76
Desvío estándar de Petal.Length: 1.77

In [22]:
print('--- Petal.Width ---')
cat(sprintf("Media de Petal.Width: %.2f\n", mean(datos$Petal.Width)))
cat(sprintf("Desvío estándar de Petal.Width: %.2f\n", sd(datos$Petal.Width)))

[1] "--- Petal.Width ---"
Media de Petal.Width: 1.20
Desvío estándar de Petal.Width: 0.76

8) Tomar una muestra pequeña de 10 flores
set.seed(123)  
La función **set.seed** permite reproducir la misma muestra en cada ejecución.

muestra <- iris[sample(1:nrow(iris), 10), ]

9) Calcular la media muestral del Largo del Sépalo
media_muestral <- mean(muestra$Sepal.Length)

10) Calcular la media de toda la población (dataset completo como población)
media_poblacional <- mean(iris$Sepal.Length)

In [42]:
set.seed(123)

muestra <- datos[sample(1:nrow(datos), 10), ]

print('--- Muestra de 10 flores ---')
print(muestra)

cat(sprintf("Media muestral de Sepal.Length: %.2f\n", mean(muestra$Sepal.Length)))
cat(sprintf("Media poblacional de Sepal.Length: %.2f\n", mean(datos$Sepal.Length)))

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
14  4.3          3.0         1.1          0.1         setosa
50  5.0          3.3         1.4          0.2         setosa
118 7.7          3.8         6.7          2.2         virginica
43  4.4          3.2         1.3          0.2         setosa
150 5.9          3.0         5.1          1.8         virginica
148 6.5          3.0         5.2          2.0         virginica
90  5.5          2.5         4.0          1.3         versicolor
91  5.5          2.6         4.4          1.2         versicolor
143 5.8          2.7         5.1          1.9         virginica
92  6.1          3.0         4.6          1.4         versicolor

[1] 5.67

[1] 5.843333